-- ForgeAI
-- Migration 001: Users
--
-- User authentication is managed by Supabase Auth.
-- Supabase stores authenticated users in auth.users.
--
-- ForgeAI application tables reference auth.users(id).
-- No duplicate public.users table is required.